version: '3.8'

services:
  pmll-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pmll-api
    ports:
      - "8001:8001"
    environment:
      - PMLL_HOST=0.0.0.0
      - PMLL_PORT=8001
      - PMLL_DEVICE=cpu
      - PMLL_ENVIRONMENT=production
      - LOG_LEVEL=info
    volumes:
      - ../data:/app/data
      - ../config:/app/config
      - ../logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: pmll-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: pmll-postgres
    environment:
      POSTGRES_DB: pmll
      POSTGRES_USER: pmll_user
      POSTGRES_PASSWORD: pmll_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmll_user -d pmll"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  postgres_data: