name: GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'registry/**', '.github/workflows/pages.yml' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write         # for actions/deploy-pages
      id-token: write      # to verify deployment
    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: |
          mkdir _site
          cp -r docs/* _site/
          # If registry artefacts exist (built by registry workflow) copy them in
          if [ -d registry ]; then cp -r registry _site/; fi

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: 📤 Deploy to gh-pages
        uses: actions/deploy-pages@v4
